/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.provaexerc01;

/**
 *
 * @author ADMIN
 */
public class Prova2 extends javax.swing.JFrame {

    /**
     * Creates new form Prova2
     */
    public Prova2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botao = new javax.swing.JButton();
        precoProduto = new javax.swing.JTextField();
        precosolucao1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        precoeconomia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mensagemComMensal = new javax.swing.JLabel();
        mensagemComAnual = new javax.swing.JLabel();
        resultadomensal = new javax.swing.JLabel();
        resultadoanual = new javax.swing.JLabel();
        resultadoporcentagem = new javax.swing.JLabel();
        produtomensalmente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mensagemSemAnual = new javax.swing.JLabel();
        mensagemSemMensal = new javax.swing.JLabel();
        semsolucao = new javax.swing.JLabel();
        comsolucao = new javax.swing.JLabel();
        Semresultadomensal = new javax.swing.JLabel();
        comLucro = new javax.swing.JLabel();
        Semresultadoanualmente = new javax.swing.JLabel();
        mensagemLucroMensal = new javax.swing.JLabel();
        lucroMensal = new javax.swing.JLabel();
        mensagemLucroAnual = new javax.swing.JLabel();
        lucroAnual = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Bem Vindo a calculadora ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Preço do Produto");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Preço da solução(mensalmente)");

        botao.setBackground(new java.awt.Color(102, 102, 102));
        botao.setForeground(new java.awt.Color(0, 51, 204));
        botao.setText("Ver o lucro");
        botao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        precoProduto.setBackground(new java.awt.Color(0, 51, 204));
        precoProduto.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        precoProduto.setForeground(new java.awt.Color(255, 255, 255));
        precoProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        precosolucao1.setBackground(new java.awt.Color(0, 51, 204));
        precosolucao1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        precosolucao1.setForeground(new java.awt.Color(255, 255, 255));
        precosolucao1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        precosolucao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precosolucao1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Lucro(por cada produto)");

        precoeconomia.setBackground(new java.awt.Color(0, 51, 204));
        precoeconomia.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        precoeconomia.setForeground(new java.awt.Color(255, 255, 255));
        precoeconomia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Porcentagem");

        mensagemComMensal.setText("Mensalmente :");

        mensagemComAnual.setText("Anualmente :");

        resultadomensal.setText("R$");

        resultadoanual.setText("R$");

        produtomensalmente.setBackground(new java.awt.Color(0, 51, 204));
        produtomensalmente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        produtomensalmente.setForeground(new java.awt.Color(255, 255, 255));
        produtomensalmente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Quantidade produto vendido mensalmente");

        mensagemSemAnual.setText("Anualmente :");

        mensagemSemMensal.setText("Mensalmente :");

        semsolucao.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        semsolucao.setText("SEM NOSSA SOLUÇÃO");

        comsolucao.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        comsolucao.setText("COM NOSSA SOLUÇÃO");

        Semresultadomensal.setText("R$");

        comLucro.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        comLucro.setText("LUCRO");

        Semresultadoanualmente.setText("R$");

        mensagemLucroMensal.setText("Mensalmente :");

        lucroMensal.setText("R$");

        mensagemLucroAnual.setText("Anualmente :");

        lucroAnual.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(220, 220, 220))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precosolucao1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 540, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precoeconomia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mensagemSemAnual)
                                        .addGap(8, 8, 8)
                                        .addComponent(Semresultadoanualmente))
                                    .addComponent(semsolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mensagemSemMensal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Semresultadomensal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(botao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mensagemComMensal)
                                                    .addComponent(mensagemComAnual))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(resultadoanual)
                                                    .addComponent(resultadomensal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(comsolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mensagemLucroAnual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lucroAnual))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(comLucro)
                                                    .addComponent(mensagemLucroMensal))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lucroMensal))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(produtomensalmente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultadoporcentagem)))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoporcentagem)
                    .addComponent(produtomensalmente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precosolucao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precoeconomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(botao)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comsolucao)
                    .addComponent(semsolucao)
                    .addComponent(comLucro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensagemSemMensal)
                    .addComponent(mensagemComMensal)
                    .addComponent(resultadomensal, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(mensagemLucroMensal)
                    .addComponent(lucroMensal)
                    .addComponent(Semresultadomensal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mensagemSemAnual)
                        .addComponent(Semresultadoanualmente)
                        .addComponent(mensagemLucroAnual)
                        .addComponent(lucroAnual))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mensagemComAnual)
                        .addComponent(resultadoanual)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precosolucao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precosolucao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precosolucao1ActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        Double Produto = Double.valueOf(precoProduto.getText());
        Double PrecoSolucao = Double.valueOf(precosolucao1.getText());
        Double QntMensal = Double.valueOf(produtomensalmente.getText());
        Double Economia = Double.valueOf(precoeconomia.getText());
        
        Double Economia1 = Economia * QntMensal;
        Double PrecoSolucao1 = PrecoSolucao * 12 ;
        Double salario = Produto * QntMensal ;
        Double anual = salario * 12 ;
        Semresultadomensal.setText(String.format("R$%.2f",(salario)));
        Semresultadoanualmente.setText(String.format("R$%.2f",(anual)));
        
        Double mensal = salario + Economia1 - PrecoSolucao ;
        Double anualSolucao = (mensal * 12) + PrecoSolucao1 ;
        
        resultadomensal.setText(String.format("R$ %.2f",(mensal)));
        resultadoanual.setText(String.format("R$ %.2f",(anualSolucao)));
        
        Double Lucro = mensal - salario ;
        Double LucroAnual = anualSolucao - anual ;
        
        lucroMensal.setText(String.format("R$ %.2f",(Lucro)));
        lucroAnual.setText(String.format("R$ %.2f",(LucroAnual)));
        
        semsolucao.setText("Sem Solução");
        mensagemSemMensal.setText("Mensalmente :");
        mensagemSemAnual.setText("Anual :");
        
        comsolucao.setText("Com Solução");
        mensagemComMensal.setText("Mensalmente :");
        mensagemComAnual.setText("Anual :");
        
        comLucro.setText("Lucro");
        mensagemLucroMensal.setText("Mensalmente :");
        mensagemLucroAnual.setText("Anual :");
        
        Double porcentagem = (Lucro  * 100) / salario;
        
        resultadoporcentagem.setText(String.format("%.0f %%",(porcentagem)));
        
        
    }//GEN-LAST:event_botaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prova2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prova2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prova2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prova2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prova2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Semresultadoanualmente;
    private javax.swing.JLabel Semresultadomensal;
    private javax.swing.JButton botao;
    private javax.swing.JLabel comLucro;
    private javax.swing.JLabel comsolucao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lucroAnual;
    private javax.swing.JLabel lucroMensal;
    private javax.swing.JLabel mensagemComAnual;
    private javax.swing.JLabel mensagemComMensal;
    private javax.swing.JLabel mensagemLucroAnual;
    private javax.swing.JLabel mensagemLucroMensal;
    private javax.swing.JLabel mensagemSemAnual;
    private javax.swing.JLabel mensagemSemMensal;
    private javax.swing.JTextField precoProduto;
    private javax.swing.JTextField precoeconomia;
    private javax.swing.JTextField precosolucao1;
    private javax.swing.JTextField produtomensalmente;
    private javax.swing.JLabel resultadoanual;
    private javax.swing.JLabel resultadomensal;
    private javax.swing.JLabel resultadoporcentagem;
    private javax.swing.JLabel semsolucao;
    // End of variables declaration//GEN-END:variables
}
